version: "3"

services:
  api:
    build:
      context: ./api
    ports:
      - 1323:80
    environment:
      - EXPORTER_ENDPOINT=otel-collector:4318
      - OTEL_SERVICE_NAME="open-ads-api"
    depends_on:
      - otel-collector

  kong:
    image: kong:latest
    container_name: dbless_kong
    restart: always
    environment:
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1.0
    volumes:
      - ./kong/kong.yml:/kong/declarative/kong.yaml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8005:8005"
      - "8006:8006"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
    depends_on:
      - api
      - otel-collector

  jaeger:
    image: "jaegertracing/all-in-one:1.42"
    ports:
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector:0.67.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318"
      - "55679:55679"
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    links:
      - api:api
      - kong:kong
    volumes:
     - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
     - 'prometheus-data:/prometheus'

  grafana:
    image: grafana/grafana:9.5.15
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus

volumes:
  prometheus-data: {}