_format_version: "1.1"

services:
  - name: example_service
    url: http://host.docker.internal/users
    routes:
      - name: users
        paths:
          - /users
    plugins:
      - name: rate-limiting
        config:
          second: 10000
          hour: 1000000
          policy: local
      - name: opentelemetry
        config:
          endpoint: http://otel-collector:4318/v1/traces
          resource_attributes:
            service.name: kong-dev-users
plugins:
- name: prometheus
  config:
    per_consumer: true
    status_code_metrics: true
    latency_metrics: true
    bandwidth_metrics: true
    upstream_health_metrics: true
